def gen_2o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    h = state.local_var[2]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(a > b)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)


def gen_4o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    h = state.local_var[4]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)


def gen_4o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    h = state.local_var[4]
    i = state.local_var[5]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != h)


def gen_4o3u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    h = state.local_var[4]
    i = state.local_var[5]
    j = state.local_var[6]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != h)
    state.constraints.append(j != a)
    state.constraints.append(j != b)
    state.constraints.append(j != c)
    state.constraints.append(j != d)
    state.constraints.append(j != h)
    state.constraints.append(j != i)


def gen_5o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    h = state.local_var[5]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)


def gen_5o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    h = state.local_var[5]
    i = state.local_var[6]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != h)


def gen_5o3u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    h = state.local_var[5]
    i = state.local_var[6]
    j = state.local_var[7]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != h)
    state.constraints.append(j != a)
    state.constraints.append(j != b)
    state.constraints.append(j != c)
    state.constraints.append(j != d)
    state.constraints.append(j != e)
    state.constraints.append(j != h)
    state.constraints.append(j != i)


def gen_6o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    h = state.local_var[6]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)


def gen_6o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    h = state.local_var[6]
    i = state.local_var[7]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != h)


def gen_6o3u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    h = state.local_var[6]
    i = state.local_var[7]
    j = state.local_var[8]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != h)
    state.constraints.append(j != a)
    state.constraints.append(j != b)
    state.constraints.append(j != c)
    state.constraints.append(j != d)
    state.constraints.append(j != e)
    state.constraints.append(j != f)
    state.constraints.append(j != h)
    state.constraints.append(j != i)


def gen_7o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    h = state.local_var[7]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)


def gen_7o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    h = state.local_var[7]
    i = state.local_var[8]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != g)
    state.constraints.append(i != h)


def gen_7o3u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    h = state.local_var[7]
    i = state.local_var[8]
    j = state.local_var[9]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != g)
    state.constraints.append(i != h)
    state.constraints.append(j != a)
    state.constraints.append(j != b)
    state.constraints.append(j != c)
    state.constraints.append(j != d)
    state.constraints.append(j != e)
    state.constraints.append(j != f)
    state.constraints.append(j != g)
    state.constraints.append(j != h)
    state.constraints.append(j != i)


def gen_8o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    x = state.local_var[7]
    h = state.local_var[8]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(x != a)
    state.constraints.append(x != b)
    state.constraints.append(x != c)
    state.constraints.append(x != d)
    state.constraints.append(x != e)
    state.constraints.append(x != f)
    state.constraints.append(x != g)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    state.constraints.append(g > x)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(h != x)


def gen_8o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    x = state.local_var[7]
    h = state.local_var[8]
    i = state.local_var[9]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(x != a)
    state.constraints.append(x != b)
    state.constraints.append(x != c)
    state.constraints.append(x != d)
    state.constraints.append(x != e)
    state.constraints.append(x != f)
    state.constraints.append(x != g)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    state.constraints.append(g > x)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(h != x)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != g)
    state.constraints.append(i != x)
    state.constraints.append(i != h)


def gen_9o1u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    x = state.local_var[7]
    y = state.local_var[8]
    h = state.local_var[9]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(x != a)
    state.constraints.append(x != b)
    state.constraints.append(x != c)
    state.constraints.append(x != d)
    state.constraints.append(x != e)
    state.constraints.append(x != f)
    state.constraints.append(x != g)
    state.constraints.append(y != a)
    state.constraints.append(y != b)
    state.constraints.append(y != c)
    state.constraints.append(y != d)
    state.constraints.append(y != e)
    state.constraints.append(y != f)
    state.constraints.append(y != g)
    state.constraints.append(y != x)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    state.constraints.append(g > x)
    state.constraints.append(x > y)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(h != x)
    state.constraints.append(h != y)


def gen_9o2u(state):
    a = state.local_var[0]
    b = state.local_var[1]
    c = state.local_var[2]
    d = state.local_var[3]
    e = state.local_var[4]
    f = state.local_var[5]
    g = state.local_var[6]
    x = state.local_var[7]
    y = state.local_var[8]
    h = state.local_var[9]
    i = state.local_var[10]
    # ordered variables
    state.constraints.append(a != b)
    state.constraints.append(c != a)
    state.constraints.append(c != b)
    state.constraints.append(d != a)
    state.constraints.append(d != b)
    state.constraints.append(d != c)
    state.constraints.append(e != a)
    state.constraints.append(e != b)
    state.constraints.append(e != c)
    state.constraints.append(e != d)
    state.constraints.append(f != a)
    state.constraints.append(f != b)
    state.constraints.append(f != c)
    state.constraints.append(f != d)
    state.constraints.append(f != e)
    state.constraints.append(g != a)
    state.constraints.append(g != b)
    state.constraints.append(g != c)
    state.constraints.append(g != d)
    state.constraints.append(g != e)
    state.constraints.append(g != f)
    state.constraints.append(x != a)
    state.constraints.append(x != b)
    state.constraints.append(x != c)
    state.constraints.append(x != d)
    state.constraints.append(x != e)
    state.constraints.append(x != f)
    state.constraints.append(x != g)
    state.constraints.append(y != a)
    state.constraints.append(y != b)
    state.constraints.append(y != c)
    state.constraints.append(y != d)
    state.constraints.append(y != e)
    state.constraints.append(y != f)
    state.constraints.append(y != g)
    state.constraints.append(y != x)
    state.constraints.append(a > b)
    state.constraints.append(b > c)
    state.constraints.append(c > d)
    state.constraints.append(d > e)
    state.constraints.append(e > f)
    state.constraints.append(f > g)
    state.constraints.append(g > x)
    state.constraints.append(x > y)
    # unordered variables
    state.constraints.append(h != a)
    state.constraints.append(h != b)
    state.constraints.append(h != c)
    state.constraints.append(h != d)
    state.constraints.append(h != e)
    state.constraints.append(h != f)
    state.constraints.append(h != g)
    state.constraints.append(h != x)
    state.constraints.append(h != y)
    state.constraints.append(i != a)
    state.constraints.append(i != b)
    state.constraints.append(i != c)
    state.constraints.append(i != d)
    state.constraints.append(i != e)
    state.constraints.append(i != f)
    state.constraints.append(i != g)
    state.constraints.append(i != x)
    state.constraints.append(i != y)
    state.constraints.append(i != h)


MAPPING = {
    '2o1u': gen_2o1u,
    '4o1u': gen_4o1u,
    '4o2u': gen_4o2u,
    '4o3u': gen_4o3u,
    '5o1u': gen_5o1u,
    '5o2u': gen_5o2u,
    '5o3u': gen_5o3u,
    '6o1u': gen_6o1u,
    '6o2u': gen_6o2u,
    '6o3u': gen_6o3u,
    '7o1u': gen_7o1u,
    '7o2u': gen_7o2u,
    '7o3u': gen_7o3u,
    '8o1u': gen_8o1u,
    '8o2u': gen_8o2u,
    '9o1u': gen_9o1u,
    '9o2u': gen_9o2u,
}
