from .ArithmeticInstructions import *
from .BitwiseInstructions import *
from .ConstantInstructions import *
from .ControlInstructions import *
from .ConversionInstructions import *
from .LogicalInstructions import *
from .MemoryInstructions import *
from .ParametricInstructions import *
from .VariableInstructions import *
